- text: "купити СЕС у Київській області"
  entities:
    - text: "СЕС"
      label: "СЕС"
    - text: "Київській області"
      label: "місце"
- text: "збудувати сонячну електростанцію у Львові"
  entities:
    - text: "сонячну електростанцію"
      label: "СЕС"
    - text: "Львові"
      label: "місце"
- text: "збудувати сонячну електростанцію у Львові"
  entities:
    - text: "сонячну електростанцію"
      label: "СЕС"
    - text: "Львові"
      label: "місце"
- text: "запроєктувати автономну сонячну електростанцію у Смирні"
  entities:
    - text: "автономну сонячну електростанцію"
      label: "СЕС"
    - text: "Смирні"
      label: "місце"
- text: "розкажи мені більше про види сонячних електростанцій"
  entities:
    - text: "сонячних електростанцій"
      label: "СЕС"
    - text: "види"
      label: "характеристика"
- text: "я нічого не знаю про контролери заряду"
  entities:
    - text: "контролери заряду"
      label: "елемент СЕС"
- text: "що таке інвертор?"
  entities:
    - text: "інвертор"
      label: "елемент СЕС"
