- text: "купити СЕС у Київській області"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "Київській області"
      label: "місцевість"
- text: "збудувати сонячну електростанцію у Львові"
  entities:
    - text: "сонячну електростанцію"
      label: "сфера знань СЕС"
    - text: "Львові"
      label: "місцевість"
- text: "запроєктувати автономну сонячну електростанцію у Смирні"
  entities:
    - text: "сонячну електростанцію"
      label: "сфера знань СЕС"
    - text: "автономну"
      label: "автономна"
    - text: "Смирні"
      label: "місцевість"
- text: "з яких компонентів складається мережевої СЕС"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "мережевої"
      label: "мережева"
    - text: "компонентів"
      label: "компоненти"
- text: "розкажи про мережевий вид"
  entities:
    - text: "мережевий"
      label: "мережева"
    - text: "вид"
      label: "види"
- text: "з яких елементів складається мережева СЕС"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "мережева"
      label: "мережева"
    - text: "елементів"
      label: "компоненти"
- text: "розкажи про гібридний вид СЕС"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "гібридний"
      label: "гібридна"
    - text: "вид"
      label: "види"
- text: "які складові гібридної СЕС"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "гібридної"
      label: "гібридна"
    - text: "складові"
      label: "компоненти"
- text: "з яких складових складається гібридна СЕС"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "гібридна"
      label: "гібридна"
    - text: "складових"
      label: "компоненти"
- text: "розкажи мені більше про види сонячних електростанцій"
  entities:
    - text: "сонячних електростанцій"
      label: "сфера знань СЕС"
    - text: "види"
      label: "види"
- text: "які є плюси автономних сонячних електростанцій"
  entities:
    - text: "сонячних електростанцій"
      label: "сфера знань СЕС"
    - text: "плюси"
      label: "переваги"
    - text: "автономних"
      label: "автономна"
- text: "скільки є плюсів"
  entities:
    - text: "плюсів"
      label: "переваги"
- text: "скільки є переваг"
  entities:
    - text: "переваг"
      label: "переваги"
- text: "скільки є недоліків"
  entities:
    - text: "недоліків"
      label: "недоліки"
- text: "скільки є мінусів"
  entities:
    - text: "мінусів"
      label: "недоліки"
- text: "які є переваги автономних сонячних електростанцій"
  entities:
    - text: "сонячних електростанцій"
      label: "сфера знань СЕС"
    - text: "переваги"
      label: "переваги"
    - text: "автономних"
      label: "автономна"
- text: "що потрібно для автономної СЕС"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "автономної"
      label: "автономна"
- text: "які є недоліки мережевої СЕС"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "недоліки"
      label: "недоліки"
    - text: "мережевої"
      label: "мережева"
- text: "які є мінуси мережевої СЕС"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "мінуси"
      label: "недоліки"
    - text: "мережевої"
      label: "мережева"
- text: "якими перевагами володіють гібридні СЕС?"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "перевагами"
      label: "переваги"
    - text: "гібридні"
      label: "гібридна"
- text: "якими недоліками володіють гібридні СЕС?"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "недоліками"
      label: "недоліки"
    - text: "гібридні"
      label: "гібридна"
- text: "які плюси мають гібридні СЕС?"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "плюси"
      label: "переваги"
    - text: "гібридні"
      label: "гібридна"
- text: "якими мінусами володіють гібридні СЕС?"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "мінусами"
      label: "недоліки"
    - text: "гібридні"
      label: "гібридна"
- text: "якими недоліками володіють гібридні?"
  entities:
    - text: "недоліками"
      label: "недоліки"
    - text: "гібридні"
      label: "гібридна"
- text: "перерахуй вади гібридних"
  entities:
    - text: "вади"
      label: "недоліки"
    - text: "гібридних"
      label: "гібридна"
- text: "які вади мають автономні"
  entities:
    - text: "вади"
      label: "недоліки"
    - text: "автономні"
      label: "автономна"
- text: "вада"
  entities:
    - text: "вада"
      label: "недоліки"
- text: "дефект"
  entities:
    - text: "дефект"
      label: "недоліки"
- text: "дефекти"
  entities:
    - text: "дефекти"
      label: "недоліки"
- text: "скільки є видів СЕС?"
  entities: 
    - text: "видів"
      label: "види"
    - text: "СЕС"
      label: "сфера знань СЕС"
- text: "який вид сонячної електростанції мені підходить"
  entities: 
    - text: "вид"
      label: "види"
    - text: "СЕС"
      label: "сфера знань СЕС"
- text: "які є типи фотопанелей?"
  entities: 
    - text: "типи"
      label: "типи"
    - text: "фотопанелей"
      label: "сфера знань фотопанелі"
- text: "розкажи про монокристалічний тип фотопанелей?"
  entities: 
    - text: "монокристалічний"
      label: "монокристалічний"
    - text: "тип"
      label: "типи"
    - text: "фотопанелей"
      label: "сфера знань фотопанелі"
- text: "скільки є типів?"
  entities: 
    - text: "типів"
      label: "типи"
- text: "які переваги монокристалічного типу?"
  entities: 
    - text: "типу"
      label: "типи"
    - text: "монокристалічного"
      label: "монокристалічний"
    - text: "переваги"
      label: "переваги"
- text: "полікристалічного "
  entities: 
    - text: "полікристалічного"
      label: "полікристалічний"
- text: "полікристалічний "
  entities: 
    - text: "полікристалічний"
      label: "полікристалічний"
- text: "полікристалічних фотопанелей"
  entities: 
    - text: "полікристалічних"
      label: "полікристалічний"
    - text: "фотопанелей"
      label: "сфера знань фотопанелі"
- text: "як визначити площу СЕС?"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "площа"
      label: "характеристика"
- text: "площа моєї електростанції буде 1000 кв м"
  entities:
    - text: "електростанції"
      label: "сфера знань СЕС"
    - text: "площа"
      label: "характеристика"
    - text: "1000"
      label: "число"
    - text: "кв м"
      label: "одиниця вимірювання"
- text: "3 особи"
  entities:
    - text: "3"
      label: "кількість осіб"
- text: "3 мешканців"
  entities:
    - text: "3"
      label: "кількість осіб"
    - text: "мешканців"
      label: "мешканці"
- text: "1 особа"
  entities:
    - text: "1"
      label: "кількість осіб"
- text: "1 мешканець"
  entities:
    - text: "3"
      label: "кількість осіб"
    - text: "мешканець"
      label: "мешканці"
- text: "2 особи"
  entities:
    - text: "2"
      label: "кількість осіб"
- text: "5 осіб"
  entities:
    - text: "5"
      label: "кількість осіб"
- text: "7 осіб"
  entities:
    - text: "7"
      label: "кількість осіб"
- text: "які є основні компоненти СЕС?"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "компоненти"
      label: "компоненти"
    - text: "основні"
      label: "основні"
- text: "які є додаткові компоненти СЕС?"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "компоненти"
      label: "компоненти"
    - text: "додаткові"
      label: "додаткові"
- text: "які є другорядні елементи?"
  entities:
    - text: "елементи"
      label: "компоненти"
    - text: "другорядні"
      label: "додаткові"
- text: "з яких другорядних елементів?"
  entities:
    - text: "елементів"
      label: "компоненти"
    - text: "другорядних"
      label: "додаткові"
- text: "які є головні елементи?"
  entities:
    - text: "елементи"
      label: "компоненти"
    - text: "головні"
      label: "основні"
- text: "які є загальні характеристики СЕС?"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "характеристики"
      label: "характеристики"
- text: "що таке потужність СЕС?"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "потужність"
      label: "потужність"
- text: "з якою потужністю мені потрібна інсталяція?"
  entities:
    - text: "інсталяція"
      label: "сфера знань СЕС"
    - text: "потужністю"
      label: "потужність"
- text: "мені потрібно 13 шт фотопанелей"
  entities:
    - text: "фотопанелей"
      label: "сфера знань фотопанелі"
    - text: "13"
      label: "число"
    - text: "шт"
      label: "одиниця вимірювання"
- text: "Моя СЕС буде на даху"
  entities:
    - text: "СЕС"
      label: "сфера знань СЕС"
    - text: "даху"
      label: "дах"
- text: "У мене є місце для фотопанелей на землі"
  entities:
    - text: "землі"
      label: "земля"
    - text: "фотопанелей"
      label: "сфера знань фотопанелі"
- text: "Я визначаю місце монтажу фотопанелей на землі"
  entities:
    - text: "землі"
      label: "земля"
    - text: "місце монтажу"
      label: "місце монтажу"
    - text: "фотопанелей"
      label: "сфера знань фотопанелі"
- text: "Дах буде місцем монтажу"
  entities:
    - text: "Дах"
      label: "дах"
- text: "визначення за кількістю"
  entities:
    - text: "кількістю"
      label: "кількість"
- text: "визначення за енергоспоживанням"
  entities:
    - text: "енергоспоживанням"
      label: "енергоспоживання"
- text: "список споживачів електроенергії"
  entities:
    - text: "споживачів"
      label: "споживачі"
- text: "визначити потужність за кількістю мешканців"
  entities:
    - text: "кількістю"
      label: "кількість"
    - text: "мешканців"
      label: "мешканці"
    - text: "потужність"
      label: "потужність"
- text: "визначити потужність за електроспоживанням"
  entities:
    - text: "електроспоживанням"
      label: "електроспоживання"
    - text: "потужність"
      label: "потужність"
- text: "визначення потужності за фактичним електроспоживанням"
  entities:
    - text: "потужності"
      label: "потужність"
    - text: "електроспоживанням"
      label: "електроспоживання"
- text: "які існуюють споживачі електроенергії"
  entities:
    - text: "споживачі"
      label: "споживачі"
- text: "0*"
  entities:
    - text: "0*"
      label: "0*"
- text: "кут нахилу 15*"
  entities:
    - text: "15*"
      label: "15*"
    - text: "кут нахилу"
      label: "кут нахилу"
- text: "кути нахилу 30* і 60*"
  entities:
    - text: "30*"
      label: "30*"
    - text: "60*"
      label: "60*"
    - text: "кути нахилу"
      label: "кут нахилу"
- text: "як впливає кут нахилу фотопанелей на їх ефективність?"
  entities:
    - text: "кут нахилу"
      label: "кут нахилу"
    - text: "фотопанелей"
      label: "сфера знань СЕС"
    - text: "ефективність"
      label: "ефективність"
- text: "ефективністю, фактори ефективності"
  entities:
    - text: "ефективністю"
      label: "ефективність"
    - text: "ефективності"
      label: "ефективність"
- text: "хочу зазначити, що у мене обмежена площа для СЕС."
  entities:
    - text: "площа"
      label: "характеристика"
    - text: "СЕС"
      label: "сфера знань СЕС"
- text: "елементи СЕС "
  entities:
    - text: "елементи"
      label: "компоненти"
- text: "складові інсталіція "
  entities:
    - text: "складові"
      label: "компоненти"
    - text: "інсталіція"
      label: "сфера знань СЕС"
- text: "висока температура"
  entities:
    - text: "температура"
      label: "температура"
    - text: "висока"
      label: "висока"
- text: "про оптимальну температуру"
  entities:
    - text: "температуру"
      label: "температура"
    - text: "оптимальну"
      label: "оптимальна"
- text: "які є температури крім високої"
  entities:
    - text: "температури"
      label: "температура"
    - text: "високої"
      label: "висока"
- text: "порівняй високу і оптимальну температуру"
  entities:
    - text: "температуру"
      label: "температура"
    - text: "високу"
      label: "висока"
    - text: "оптимальну"
      label: "оптимальна"
- text: "які мінуси низької температури"
  entities:
    - text: "температури"
      label: "температура"
    - text: "низької"
      label: "низька"
    - text: "мінуси"
      label: "недоліки"
- text: "як впливає орієнтація на продуктивність?"
  entities:
    - text: "орієнтація"
      label: "орієнтація"
    - text: "продуктивність"
      label: "ефективність"
- text: "яка орієнтація краща: північна, південна, східна чи західна?"
  entities:
    - text: "орієнтація"
      label: "орієнтація"
    - text: "північна"
      label: "північ"
    - text: "південна"
      label: "південь"
    - text: "східна"
      label: "схід"
    - text: "західна"
      label: "захід"
- text: "яку орієнтацію краще обрати, на північ, південь, схід чи захід?"
  entities:
    - text: "орієнтацію"
      label: "орієнтація"
    - text: "північ"
      label: "північ"
    - text: "південь"
      label: "південь"
    - text: "схід"
      label: "схід"
    - text: "захід"
      label: "захід"
- text: "високу інсоляцію"
  entities:
    - text: "інсоляцію"
      label: "інсоляція"
    - text: "високу"
      label: "висока"
- text: "інсоляція"
  entities:
    - text: "інсоляція"
      label: "інсоляція"
- text: "які є технічні показники фотопанелей?"
  entities: 
    - text: "технічні показники"
      label: "технічні показники"
    - text: "фотопанелей"
      label: "сфера знань фотопанелі"
- text: "які є тех. показники?"
  entities: 
    - text: "тех. показники"
      label: "технічні показники"
- text: "скільки є технічних показників?"
  entities: 
    - text: "технічних показників"
      label: "технічні показники"
- text: "чи вага є технічним показником?"
  entities: 
    - text: "вага"
      label: "вага"
    - text: "технічним показником"
      label: "технічні показники"
- text: "на що впливає струм у системі?"
  entities: 
    - text: "струм"
      label: "струм"
- text: "на що впливає напруга у системі?"
  entities: 
    - text: "напруга"
      label: "напруга"
- text: "які є недоліки монокристалічної і полікристалічної фотопанелі?"
  entities: 
    - text: "монокристалічної"
      label: "монокристалічний"
    - text: "полікристалічної"
      label: "полікристалічний"
- text: "як впливає помірне і стале затінення на ефективність?"
  entities: 
    - text: "помірне"
      label: "помірне"
    - text: "стале"
      label: "стале"
    - text: "затінення"
      label: "затінення"
    - text: "ефективність"
      label: "стефективністьале"
- text: "похмурі дні"
  entities: 
    - text: "похмурі дні"
      label: "похмурі дні"
- text: "спосіб зʼєднання фотопанелей може бути послідовним, паралельним і змішаним"
  entities: 
    - text: "спосіб зʼєднання"
      label: "зʼєднання"  
    - text: "фотопанелей"
      label: "сфера знань фотопанелі" 
    - text: "послідовним"
      label: "послідовне"
    - text: "паралельним"
      label: "паралельне"
    - text: "змішаним"
      label: "змішане" 
- text: "тип зʼєднання послідовний, паралельний і змішаний"
  entities: 
    - text: "тип зʼєднання"
      label: "зʼєднання"
    - text: "послідовний"
      label: "послідовне"
    - text: "паралельний"
      label: "паралельне"
    - text: "змішаний"
      label: "змішане"
- text: "зʼєднання послідовне, паралельне і змішане"
  entities: 
    - text: "зʼєднання"
      label: "зʼєднання"
    - text: "послідовне"
      label: "послідовне"
    - text: "паралельне"
      label: "паралельне"
    - text: "змішане"
      label: "змішане"
