- text: "купити СЕС у Київській області"
  entities:
    - text: "СЕС"
      label: "СЕС"
    - text: "Київській області"
      label: "місце"
- text: "збудувати сонячну електростанцію у Львові"
  entities:
    - text: "сонячну електростанцію"
      label: "СЕС"
    - text: "Львові"
      label: "місце"
- text: "збудувати сонячну електростанцію у Львові"
  entities:
    - text: "сонячну електростанцію"
      label: "СЕС"
    - text: "Львові"
      label: "місце"
- text: "запроєктувати автономну сонячну електростанцію у Смирні"
  entities:
    - text: "автономну сонячну електростанцію"
      label: "СЕС"
    - text: "Смирні"
      label: "місце"
- text: "розкажи мені більше про види сонячних електростанцій"
  entities:
    - text: "сонячних електростанцій"
      label: "СЕС"
    - text: "види"
      label: "характеристика"
- text: "що таке потужність СЕС?"
  entities:
    - text: "СЕС"
      label: "СЕС"
    - text: "потужність"
      label: "характеристика"
- text: "я нічого не знаю про контролери заряду"
  entities:
    - text: "контролери заряду"
      label: "елемент СЕС"
- text: "що таке інвертор?"
  entities:
    - text: "інвертор"
      label: "елемент СЕС"
- text: "10"
  entities:
    - text: "10"
      label: "число"
- text: "девʼять"
  entities:
    - text: "девʼять"
      label: "число"
- text: "двадцять два"
  entities:
    - text: "двадцять два"
      label: "число"
- text: "5.5"
  entities:
    - text: "5.5"
      label: "число"
- text: "7,5"
  entities:
    - text: "7,5"
      label: "число"
- text: "я не знаю"
  entities:
    - text: "я не знаю"
      label: "невідомо"
- text: "не знаю"
  entities:
    - text: "не знаю"
      label: "невідомо"
- text: "важко сказати"
  entities:
    - text: "важко сказати"
      label: "невідомо"
- text: "не можу сказати"
  entities:
    - text: "не можу сказати"
      label: "невідомо"
- text: "без поняття"
  entities:
    - text: "без поняття"
      label: "невідомо"
- text: "не впевнений"
  entities:
    - text: "не впевнений"
      label: "невідомо"