- text: "купити СЕС у Київській області"
  entities:
    - text: "СЕС"
      label: "СЕС"
    - text: "Київській області"
      label: "місцевість"
- text: "збудувати сонячну електростанцію у Львові"
  entities:
    - text: "сонячну електростанцію"
      label: "СЕС"
    - text: "Львові"
      label: "місцевість"
- text: "збудувати сонячну електростанцію у Львові"
  entities:
    - text: "сонячну електростанцію"
      label: "СЕС"
    - text: "Львові"
      label: "місцевість"
- text: "запроєктувати автономну сонячну електростанцію у Смирні"
  entities:
    - text: "автономну сонячну електростанцію"
      label: "СЕС"
    - text: "Смирні"
      label: "місцевість"
- text: "розкажи мені більше про види сонячних електростанцій"
  entities:
    - text: "сонячних електростанцій"
      label: "СЕС"
    - text: "види"
      label: "характеристика"
- text: "як визначити площу СЕС?"
  entities:
    - text: "СЕС"
      label: "СЕС"
    - text: "площа"
      label: "характеристика"
- text: "площа моєї електростанції буде 1000 кв м"
  entities:
    - text: "електростанції"
      label: "СЕС"
    - text: "площа"
      label: "характеристика"
    - text: "кв м"
      label: "одиниця вимірювання"
- text: "які є основні компоненти СЕС?"
  entities:
    - text: "СЕС"
      label: "СЕС"
    - text: "основні компоненти"
      label: "характеристика"
- text: "які є додаткові компоненти СЕС?"
  entities:
    - text: "СЕС"
      label: "СЕС"
    - text: "додаткові компоненти"
      label: "характеристика"
- text: "які є загальні характеристики СЕС?"
  entities:
    - text: "СЕС"
      label: "СЕС"
    - text: "загальні характеристики"
      label: "характеристика"
- text: "що таке потужність СЕС?"
  entities:
    - text: "СЕС"
      label: "СЕС"
    - text: "потужність"
      label: "характеристика"
- text: "я нічого не знаю про контролери заряду"
  entities:
    - text: "контролери заряду"
      label: "елемент СЕС"
- text: "мені потрібно 13 шт фотопанелей"
  entities:
    - text: "фотопанелей"
      label: "елемент СЕС"
    - text: "13"
      label: "число"
    - text: "шт"
      label: "одиниця вимірювання"
- text: "що таке інвертор?"
  entities:
    - text: "інвертор"
      label: "елемент СЕС"
- text: "Моя СЕС буде на даху"
  entities:
    - text: "на даху"
      label: "місце монтажу"
- text: "У мене є місце для фотопанелей на землі"
  entities:
    - text: "на землі"
      label: "місце монтажу"
    - text: "фотопанелей"
      label: "елемент СЕС"
- text: "Я визначаю місце монтажу фотопанелей на землі"
  entities:
    - text: "на землі"
      label: "місце монтажу"
- text: "Чи ти хочеш розмістити фотопанелі на землі біля будинку чи на даху будинку?"
  entities:
    - text: "на землі"
      label: "місце монтажу"
    - text: "на даху"
      label: "місце монтажу"
- text: "У мене є місце для фотопанелей біля будинку"
  entities:
    - text: "біля будинку"
      label: "місце монтажу"
    - text: "фотопанелей"
      label: "елемент СЕС"
- text: "Дах буде місцем монтажу"
  entities:
    - text: "Дах"
      label: "місце монтажу"
- text: "визначи площу СЕС як 125 м2"
  entities:
    - text: "площу"
      label: "характеристика"
    - text: "СЕС"
      label: "СЕС"
    - text: "125"
      label: "число"
    - text: "м2"
      label: "одиниця вимірювання"
- text: "хочу зазначити, що у мене обмежена площа для СЕС."
  entities:
    - text: "площа"
      label: "характеристика"
    - text: "СЕС"
      label: "СЕС"
- text: "1000 м кв"
  entities:
    - text: "1000"
      label: "число"
    - text: "м кв"
      label: "одиниця вимірювання"
- text: "250 м кв"
  entities:
    - text: "250"
      label: "число"
    - text: "м кв"
      label: "одиниця вимірювання"
- text: "10 кВт"
  entities:
    - text: "10"
      label: "число"
    - text: "кВт"
      label: "одиниця вимірювання"
- text: "девʼять"
  entities:
    - text: "девʼять"
      label: "число"
- text: "двадцять два"
  entities:
    - text: "двадцять два"
      label: "число"
- text: "5.5"
  entities:
    - text: "5.5"
      label: "число"
- text: "7,5 Вт"
  entities:
    - text: "7,5"
      label: "число"
    - text: "Вт"
      label: "одиниця вимірювання"
- text: "я не знаю"
  entities:
    - text: "я не знаю"
      label: "невідомо"
- text: "не знаю"
  entities:
    - text: "не знаю"
      label: "невідомо"
- text: "важко сказати"
  entities:
    - text: "важко сказати"
      label: "невідомо"
- text: "не можу сказати"
  entities:
    - text: "не можу сказати"
      label: "невідомо"
- text: "без поняття"
  entities:
    - text: "без поняття"
      label: "невідомо"
- text: "не впевнений"
  entities:
    - text: "не впевнений"
      label: "невідомо"